#
postgres:
  image: postgres
  container_name: postgres
  hostname: postgres
  # restart: always
  environment:
    # - LANG=ja_JP.utf8
    - POSTGRES_USER=post
    - POSTGRES_PASSWORD=post
  volumes:
    - ./VOL/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./VOL/var/lib/postgresql/data:/var/lib/postgresql/data
  ports:
    - 5432:5432
  # command: localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.utf8
